apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-exercise-demo
spec:
  destination:
    name: ""
    namespace: ""
    server: "https://kubernetes.default.svc"
  source:
    path: 2_k8s/kustomization/litecoin-exercise-demo
    repoURL: "https://github.com/suren-m/devops-exercise.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
