apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - ../base
patchesStrategicMerge:
  - overrides.yml
namespace: devops-exercise
commonLabels:
  environment: demo
# kustomize edit set image surenmcode/litecoin=surenmcode/litecoin:0.18.1
images:
  - name: surenmcode/litecoin
    newName: surenmcode/litecoin
    newTag: latest
