apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoin
spec:
  replicas: 1
  volumeClaimTemplates:
    - metadata:
        name: litecoin-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
