apiVersion: v1
kind: Service
metadata:
  name: litecoin-svc
  labels:
    app: litecoin
spec:
  ports:
    - port: 9333
    - port: 19335
    - port: 19444

  clusterIP: None
  selector:
    app: litecoin
